name: CI/CD Pipeline for Feedback API

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main # Run on any push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner for GitHub Actions

    steps:
    # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  

    # Set up Python for dependency installation
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

    # Install project dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t feedback-api .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  # Login to Azure using the credentials stored in GitHub Secrets
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  # Login to Azure Container Registry
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name feedbackregistry
  
  # Push Docker image to Azure Container Registry (ACR)
    - name: Tag and push Docker image to ACR
      run: |
        docker tag feedback-api feedbackregistry.azurecr.io/feedback-api-repo:latest
        docker push myfeedbackregistry.azurecr.io/feedback-api-repo:latest
